tests/mainTest.py::footer::testOpenHours
--------------------------------------------------------------------
Last Page: file:///C:/Users/leon.loov/Documents/GitHub/Bengans-Biluthyrning/index.html
  Browser: chrome (105.0.5195.102)
   Driver: chromedriver (105.0.5195.52)
Timestamp: 1663146401  (Unix Timestamp)
     Date: Wednesday, 14 September 2022
     Time: 11:06:41 AM  (VÃ¤steuropa, sommartid, UTC+01:00)
--------------------------------------------------------------------
Traceback: File "C:\Users\leon.loov\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\leon.loov\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\leon.loov\Documents\GitHub\Bengans-Biluthyrning\tests\mainTest.py", line 56, in testOpenHours
    raise NameError(f"{i[:-1]} not correct")
Exception: Vardagar not correct